import esbuild from "esbuild";
import fs from 'fs';
import process from "process";
import builtins from 'builtin-modules';
import sass from "sass";
import autoprefixer from "autoprefixer";
import postcss from "postcss";
import cssnano from "cssnano";
import defaultPreset from "cssnano-preset-default";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/joethei/obisidian-rss
*/
`;

const prod = (process.argv[2] === 'production');

const verbose = Boolean(process.env.VERBOSE_SCSS);

const copyMinifiedCSS = {
    name: 'minify-css',
    setup: (build) => {
        build.onEnd(async () => {
            if (verbose) {
                console.log('[scss] Iniciando compilación SCSS main.scss');
                console.time('[scss] Tiempo compilación');
            }
            let css;
            try {
                const r = sass.compile('src/style/main.scss', {
                    style: prod ? 'compressed' : 'expanded',
                    logger: {
                        warn(message, opts) {
                            console.warn('[scss][warn]', message, opts?.span?.url ? `@ ${opts.span.url}:${opts.span.start.line+1}` : '');
                        }
                    }
                });
                css = r.css;
            } catch (err) {
                console.error('[scss][error] Falló la compilación SCSS');
                console.error(err);
                return; // no continuar para evitar escribir archivo corrupto
            }
            if (verbose) {
                console.timeEnd('[scss] Tiempo compilación');
                console.log('[scss] Longitud CSS base:', css.length.toLocaleString(),'bytes');
            }
            let result;
            if (prod) {
                const content = `${banner}\n${css}`;
                const preset = defaultPreset({discardComments: false});
                if (verbose) console.log('[scss] Aplicando autoprefixer + cssnano');
                result = await postcss([cssnano({
                    preset: preset,
                    plugins: [
                        autoprefixer,
                    ]
                })]).process(content, { from: 'src/style/main.scss' });
            } else {
                const content = `${banner}\n${css}`;
                if (verbose) console.log('[scss] Aplicando autoprefixer (modo dev)');
                result = await postcss([autoprefixer]).process(content, { from: 'src/style/main.scss' });
            }

            // Base SCSS output
            fs.writeFileSync('build/styles.css', result.css, {encoding: 'utf-8'});
            if (verbose) {
                console.log('[scss] Escrito build/styles.css tamaño final:', result.css.length.toLocaleString(),'bytes');
            }
            // If esbuild produced a component css bundle (main.css), append & remove
            try {
                if (fs.existsSync('build/main.css')) {
                    const compCss = fs.readFileSync('build/main.css','utf-8');
                    fs.appendFileSync('build/styles.css','\n/* Component CSS */\n'+compCss,'utf-8');
                    fs.unlinkSync('build/main.css');
                    if (verbose) console.log('[scss] CSS de componentes inyectado');
                }
            } catch (e) { if (verbose) console.warn('[scss] No se pudo anexar main.css', e?.message); }
        })
    }
}

const copyManifest = {
    name: 'copy-manifest',
    setup: (build) => {
        build.onEnd(() => {
            fs.copyFileSync('manifest.json', 'build/manifest.json');
        });
    },
};


// Se definen todas las opciones de compilación en un objeto.
const buildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: ['obsidian', 'electron', ...builtins],
    plugins: [sveltePlugin({
        preprocess: sveltePreprocess(),
        emitCss: false // inline component CSS to avoid separate main.css
    }), copyManifest, copyMinifiedCSS],
    format: 'cjs',
    target: 'es2016',
    logLevel: verbose ? 'debug' : 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'build/main.js',
};

// Se usa una lógica condicional para compilar o vigilar cambios.
if (prod) {
    // Modo producción: solo compila una vez.
    esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
    // Modo desarrollo: usa el nuevo context API para el modo "watch".
    esbuild.context(buildOptions).then(ctx => {
        console.log("Watching for changes...");
        ctx.watch();
    }).catch(() => process.exit(1));
}